openapi: "3.0.0"
info:
  title: BudgetTracker API
  description: It's a simple description in order to understand how it works :)
  contact:
    name: Vadim
    url: http://localhost:8080/
    email: vadimbelaev002@gmail.com
  version: 1.1.0