-- create table categories (
--                             id bigserial primary key  ,
--                             name varchar(100) ,
--                             section varchar(100) ,
--                             color varchar(100) ,
--                             logo varchar(100) ,
--     user_id bigint references users(id)
-- );
