-- create table operations (
--                             id bigserial primary key  ,
--                             created_date date ,
--                             amount real  ,
--                             user_id bigint references users(id)  ,
--                             category_name varchar(100) references categories(name)
-- );