-- create table confirmation (
--                               id bigserial primary key  ,
--                               code varchar(100) ,
--                               user_id bigint references users(id)
-- );